name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci

jobs:
  check-versions-monorepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check versions
        run: just check-monorepo-versions

  contracts-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Forge build
        run: |
          just build-contracts
        id: build

      - name: Run Forge tests
        run: |
          just test-contracts
        id: test
  
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout=5m

      - name: Install dependencies
        run: go mod download

      - name: Run linter
        run: just lint-go

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: just test-go
        env:
          SUPERSIM_RPC_URL_OP: ${{ vars.SUPERSIM_RPC_URL_OP }}
          SUPERSIM_RPC_URL_BASE: ${{ vars.SUPERSIM_RPC_URL_BASE }}

          jobs:
  test:
    runs-on: ubuntu-latest
    services:
      anvil:
        image: ethereum/anvil
        options: --memory=8g  # Increase memory limit to 8GB
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run tests
        run: go test ./...
